name: C/C++ CI

on: [ push, pull_request ]

jobs:
  add-conan-remote:
    name: Add conan remote
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest

  build-and-test:
    name: Build and launch tests
    needs: [ add-conan-remote ]
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest

    steps:
      - uses: actions/checkout@v2

      - name: "Add conan remote (bincrafters)"
        run: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

      - name: Build
        run: ./build.sh

      - name: Launch tests
        shell: bash
        run: cd build && ctest
